Сделал дз
Skaletto07/Chat pull request #2
Opened 2022-04-26 11:12 UTC by Skaletto07

Сначала вообще не так начал делать, поэтому лишние методы присутствуют.
В итоге добавил те же данные для аутентификации в базу данных, добавил смену ника, но она отображается в чате только после перезагрузки клиента.

2022-04-29 14:19 UTC, efserg requested changes
Нет, надо отрефакторить. Пока не принимаю

2022-04-29 14:19 UTC, efserg commented on ru.gb.chat_0_2/src/main/java/ru/gb/chat/server/ChatServer.java
> +             AuthService authService = new InMemoryAuthService()) {
При чем тут вообще InMemoryAuthService? Мы же добавляем аутентификацию через БД

2022-04-29 14:19 UTC, efserg commented on ru.gb.chat_0_2/src/main/java/ru/gb/chat/SQL/JdbcApp.java
> +        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:javadb.db");
Вы на каждый запрос будете коннект к базе пересоздавать? Такое себе решение

2022-05-02 18:13 UTC, Skaletto07 commented on ru.gb.chat_0_2/src/main/java/ru/gb/chat/SQL/JdbcApp.java
> +        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:javadb.db");
Создал общий коннект, но теперь вылезла проблема, не дает зайти больше 2х клиентов, типа не правильный логин или пароль, хз как исправить

2022-05-04 04:19 UTC, efserg approved these changes

2022-05-06 14:19 UTC, Skaletto07 commented
Сделал дз, где Executers и ABC.
Как правильно работать с executers я не понял, поменять треды, поменял, но теперь, при вводе неправильного пароля, или попытаться зайти в уже авторизованного пользователя, просто выкидывает из клиента, так как они стали не деман потоками, сами не останавливаются.
Плюс на клиентах иногда вылезает такая ошибка:  Exception in thread "Thread-3" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-3.

2022-05-08 05:19 UTC, efserg requested changes

2022-05-08 05:19 UTC, efserg commented on ru.gb.chat_0_2/src/main/java/ru/gb/chat/server/ClientHandler.java
> +    ExecutorService clientHandlerES = Executors.newCachedThreadPool();
А зачем вам тут newCachedThreadPool? Вы в нем ровно один поток запускаете.

2022-05-11 13:14 UTC, merged